//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IZipCodeService")]
public interface IZipCodeService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZipCodeService/Lookup", ReplyAction="http://tempuri.org/IZipCodeService/LookupResponse")]
    string Lookup(string caller, string zipcode);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IZipCodeServiceChannel : IZipCodeService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ZipCodeServiceClient : System.ServiceModel.ClientBase<IZipCodeService>, IZipCodeService
{
    
    public ZipCodeServiceClient()
    {
    }
    
    public ZipCodeServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ZipCodeServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ZipCodeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ZipCodeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string Lookup(string caller, string zipcode)
    {
        return base.Channel.Lookup(caller, zipcode);
    }
}
